language: node_js

node_js:
  - '10'
  - '12'

branches:
  only:
    - master

install:
  - npm install

script:
  - npm run build
  - npm run generate
deploy:
  provider: heroku
  api_key: 7fe6e737-063b-40aa-83fd-79377c3f4858
  app: clinic-project
